apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  namespace: intensivo-app
  labels:
    app: intensivo-app
spec:
  selector:
    matchLabels:
      app: catalog

  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
        - name: catalog
          image: nrsjnet/intensivo-catalog
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: PRODUCT_URL
              value: "http://product-service:8081"

---

apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  namespace: intensivo-app
  labels:
    app: catalog-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8082
  selector:
    app: catalog
