apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: intensivo-app
spec:
  selector:
    matchLabels:
      app: rabbitmq

  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: "nrsjnet/intensivo-rabbitmq:v2"
          imagePullPolicy: Never
          ports:
            - containerPort: 15672
            - containerPort: 5672

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-service
  namespace: intensivo-app
  labels:
    app: rabbitmq-service
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 15672
    - name: amqp
      protocol: TCP
      port: 5672
  selector:
    app: rabbitmq
