version: '3'
services:

  rabbit:
    container_name: intensivo-microservices-rabbitmq
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
  redis:
    container_name: intensivo-microservices-redis
    image: 'redis:latest'
    ports:
      - "6379:6379"