export RABBITMQ_DEFAULT_USER="rabbitmq"
export RABBITMQ_DEFAULT_PASS="rabbitmq"
export RABBITMQ_DEFAULT_HOST=localhost
export RABBITMQ_DEFAULT_PORT=5672
export RABBITMQ_DEFAULT_VHOST="/"
export PRODUCT_HOST=http://localhost:8081